/**
 *
 * Process Editor - Simulation Reporting Package
 *
 * (C) 2008,2009 Frank Puhlmann
 *
 * http://frapu.net
 *
 */
package net.frapu.code.simulation.petrinets.reporting;

import java.awt.Color;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import java.util.StringTokenizer;
import net.frapu.code.simulation.petrinets.LaneReport;
import net.frapu.code.simulation.petrinets.PetriNetSimulation;
import net.frapu.code.simulation.petrinets.PetriNetSimulationListener;
import net.frapu.code.visualization.ProcessEditor;
import net.frapu.code.visualization.ProcessNode;
import net.frapu.code.visualization.reporting.BarChart;
import net.frapu.code.visualization.reporting.ReportingModel;

/**
 *
 * @author fpu
 */
public class FlowTimeReporting extends javax.swing.JPanel implements PetriNetSimulationListener {

	private static final long serialVersionUID = -9162514020587672347L;
	private ProcessEditor editor;
    private ReportingModel model;
    private PetriNetSimulation sim;

    private BarChart chart1;
    private Set<ProcessNode> lanes = new HashSet<ProcessNode>();

    /** Creates new form CostReporting */
    public FlowTimeReporting(PetriNetSimulation sim) {
        // Initialize components
        initComponents();
        initCustomComponents();
        // Register listener
        this.sim = sim;
        sim.addListener(this);
    }

    public void initCustomComponents() {
        // Initialize model
        model = new ReportingModel("Flow Times");

        chart1 = new BarChart();
        chart1.setSize(400, 300);
        chart1.setPos(230, 180);
        chart1.setProperty(BarChart.PROP_BARCOLOR, ""+
                (new Color(192,64,64).getRGB())+","+
                (new Color(64,192,64).getRGB()));

        chart1.setText("Flow Times");
        chart1.setXLabel("Instances");
        chart1.setYLabel("Time (min)");
        chart1.setProperty(BarChart.PROP_VALUES, "");
        chart1.setProperty(BarChart.PROP_LABELS, "");

        model.addNode(chart1);

        // Create editor and add to ViewportView
        editor = new ProcessEditor(model);
        jScrollPane1.setViewportView(editor);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void refreshDisplay() {
        // ignore
    }

    public void simulationFinished() {
        // Update values here
        List<List<Integer>> data = new LinkedList<List<Integer>>();
        // Add data for all instances
        StringTokenizer duration =
                new StringTokenizer(sim.getSimulationResult(PetriNetSimulation.SIM_MAX_DUR_DATA), ",");
        StringTokenizer waitings =
                new StringTokenizer(sim.getSimulationResult(PetriNetSimulation.SIM_MAX_WAIT_DATA), ",");
        while (duration.hasMoreTokens() && waitings.hasMoreTokens()) {
            LinkedList<Integer> values = new LinkedList<Integer>();
            data.add(values);
            try {
                values.add((int) (Double.parseDouble(waitings.nextToken())));
                values.add((int) (Double.parseDouble(duration.nextToken())));
            } catch (Exception e) {
                chart1.setErrorMessage("Error retrieving results");
            }
        }
        chart1.setStackedData(data);
        repaint();

        // Remove all Lane reports
        for (ProcessNode n : lanes) {
            model.removeNode(n);
        }

        // Create new Lane reports
        final int SPACING = 20;
        int yPos = chart1.getPos().y + chart1.getSize().height + SPACING;
        for (LaneReport r : sim.getLaneReports()) {
            // Create chart
            BarChart chart = new BarChart();
            chart.setSize(400, 300);
            chart.setPos(230, yPos);
            chart.setText("Durations for Lane " + r.getLaneName());
            chart.setProperty(BarChart.PROP_LABELS, "Agv,Min,Max");
            chart.setXLabel("Type");
            chart.setYLabel("Time (min)");
            chart.setProperty(BarChart.PROP_BARCOLOR, ""+(new Color(128,192,128).getRGB()));
            // Update values
            List<Integer> data2 = new LinkedList<Integer>();
            try {
                data2.add((int) Double.parseDouble(r.getLaneResult(LaneReport.LANE_DUR_AVG)));
                data2.add((int) Double.parseDouble(r.getLaneResult(LaneReport.LANE_DUR_MIN)));
                data2.add((int) Double.parseDouble(r.getLaneResult(LaneReport.LANE_DUR_MAX)));
            } catch (Exception e) {
                chart.setErrorMessage("Error retrieving results");
            }
            chart.setData(data2);

            // Add chart to model
            model.addNode(chart);
            // Add chart to lanes
            lanes.add(chart);
            // Increase Y-Counter
            yPos += chart.getSize().height + SPACING;
        }

        editor.setSize(editor.getSize().width, editor.getSize().height+SPACING);

        repaint();
    }

    public void simulationStarted() {
        // Reset values
        chart1.setData(null);
        // Remove all Lane reports
        for (ProcessNode n : lanes) {
            model.removeNode(n);
        }
        lanes.clear();
        repaint();
    }
}
