/**
 *
 * Process Editor - Simulation Reporting Package
 *
 * (C) 2008,2009 Frank Puhlmann
 *
 * http://frapu.net
 *
 */
package net.frapu.code.simulation.petrinets.reporting;

import java.awt.Image;
import java.awt.Toolkit;
import net.frapu.code.simulation.petrinets.PetriNetSimulation;

/**
 *
 * @author fpu
 */
public class SimulationReportingFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = -6060180716258568067L;
	//private PetriNetSimulation sim;

    /** Creates new form SimulationReportingFrame */
    public SimulationReportingFrame(PetriNetSimulation sim) {
        initComponents();
        initCustomComponents(sim);
    }

    public void initCustomComponents(PetriNetSimulation sim) {
        Toolkit tk = this.getToolkit();
        Image image = tk.getImage(getClass().getResource("/menu/icon_16x16_barchart.gif"));
        while (!tk.prepareImage(image, -1, -1, this)) {
            try {
                Thread.sleep(100);
            } catch (Exception e) {
            }
        }
        this.setIconImage(image);

        jTabbedPane1.add("Costs", new CostReporting(sim));
        jTabbedPane1.add("Flow Time", new FlowTimeReporting(sim));
        jTabbedPane1.add("Flow Rate", new FlowRateReporting(sim));
        jTabbedPane1.add("Inventory", new InventoryReporting(sim));
        jTabbedPane1.add("Labor", new LaborReporting(sim));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Simulation Reporting");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
