/**
 *
 * Process Editor - inubit Workbench Package
 *
 * (C) 2009, 2010 inubit AG
 * (C) 2014 the authors
 * 
 */
package com.inubit.research.gui;

import java.awt.event.ActionEvent;
import javax.swing.JFileChooser;
import javax.swing.JTextField;

import com.inubit.research.animation.LayoutingAnimator;
import com.inubit.research.layouter.LayoutHelper;
import com.inubit.research.server.ProcessEditorServer;
import com.inubit.research.server.ProcessEditorServerHelper;
import java.awt.Color;

import net.frapu.code.converter.XSDImporter;
import net.frapu.code.visualization.Configuration;

/**
 *
 * @author fpu
 */
public class WorkbenchConfigurationDialog extends javax.swing.JDialog {

    /**
     *
     */
    private static final long serialVersionUID = 3675984304394777610L;

    /** Creates new form WorkbenchConfigurationDialog */
    public WorkbenchConfigurationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initProperties();
    }

    private void checkNumericKey(JTextField field) {
        if (field.getText().length() > 0) {
            char _typed = field.getText().charAt(field.getText().length() - 1);
            if (!(_typed >= '0' && _typed <= '9')) {
                field.setText(field.getText().substring(0, field.getText().length() - 1));
            }
        }
    }

    private void initProperties() {
        // Get parameters from configuration and show them
        Configuration conf = Configuration.getInstance();
        serverTextField.setText(conf.getProperty(WorkbenchConnectToServerDialog.CONF_SERVER_URI, "http://localhost:1205"));
        userTextField.setText(conf.getProperty(WorkbenchConnectToServerDialog.CONF_SERVER_USER, "root"));
        passwordField.setText(conf.getProperty(WorkbenchConnectToServerDialog.CONF_SERVER_PASSWORD, "inubit"));
        pathToDotTextField.setText(conf.getProperty(Configuration.PROP_DOT_LOCATION).replace("\\\\", "\\"));
        useSystemLookAndFeelCheckbox.setSelected(conf.getProperty(Configuration.PROP_USE_SYSTEM_LOOK_AND_FEEL, "0").equals("1"));
        showSimpleTypes.setSelected(conf.getProperty(XSDImporter.CONF_SHOW_SIMPLE_CLASSES, "1").equals("1"));
        showEnumerations.setSelected(conf.getProperty(XSDImporter.CONF_SHOW_ENUMERATIONS, "1").equals("1"));
        showExternalBaseClasses.setSelected(conf.getProperty(XSDImporter.CONF_SHOW_EXTERNAL_BASES_TYPES, "0").equals("1"));
        showSimpleTypesActionPerformed(new ActionEvent(this, 0, null));
        colorCodeStereotypes.setSelected(conf.getProperty(XSDImporter.CONF_COLOR_CODE_STEREOTYPES, "0").equals("1"));
        shortenEdgesBox.setSelected(!conf.getProperty(LayoutHelper.CONF_SHORTEN_EDGES).equals("0"));
        centerNodesbox.setSelected(!conf.getProperty(LayoutHelper.CONF_CENTER_NODES).equals("0"));
        animationSpeedTextField.setText(conf.getProperty(LayoutingAnimator.CONF_ANIMATION_SPEED, "6000"));
        xdistanceTextFieldUML.setText(conf.getProperty(LayoutHelper.CONF_X_DISTANCE_SUGI, "30"));
        yDistanceTextFieldUML.setText(conf.getProperty(LayoutHelper.CONF_Y_DISTANCE_SUGI, "35"));
        xdistanceTextFieldBPMN.setText(conf.getProperty(LayoutHelper.CONF_X_DISTANCE_GRID, "30"));
        yDistanceTextFieldBPMN.setText(conf.getProperty(LayoutHelper.CONF_Y_DISTANCE_GRID, "35"));
        twfWidthTextField.setText(conf.getProperty(LayoutHelper.CONF_MAX_TWF_WIDTH, "800"));
        f_cbRectEdges.setSelected(conf.getProperty(LayoutHelper.CONF_RECTIFY).equals("1"));
        f_CBsyncPools.setSelected(conf.getProperty(LayoutHelper.CONF_SYNC_POOLS).equals("1"));
        f_CBRouteMSF.setSelected(conf.getProperty(LayoutHelper.CONF_ROUTE_MESSAGEFLOW).equals("1"));
        tfLayerDistance.setText(conf.getProperty(LayoutHelper.CONF_RADIAL_LAYER_DISTANCE));
        cbSetConnectionPoints.setSelected(conf.getProperty(LayoutHelper.CONF_SET_CONNECTION_POINTS).equals("1"));
        cbScatterEdges.setSelected(conf.getProperty(LayoutHelper.CONF_SCATTER_EDGES).equals("1"));
        startServerBox.setSelected(conf.getProperty(ProcessEditorServer.CONF_SERVER_START_AT_WB_STARTUP).equals("1"));
        portField.setText(conf.getProperty(ProcessEditorServer.CONF_SERVER_PORT));
        httpsBox.setSelected(conf.getProperty(ProcessEditorServerHelper.CONF_SERVER_SECURE).equals("1"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        serverTextField = new javax.swing.JTextField();
        userTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        useSystemLookAndFeelCheckbox = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        lPathToDot = new javax.swing.JLabel();
        pathToDotTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        animationSpeedTextField = new javax.swing.JTextField();
        lAnimationSpeed = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        shortenEdgesBox = new javax.swing.JCheckBox();
        centerNodesbox = new javax.swing.JCheckBox();
        lxDistanceUML = new javax.swing.JLabel();
        lyDistanceUML = new javax.swing.JLabel();
        yDistanceTextFieldUML = new javax.swing.JTextField();
        xdistanceTextFieldUML = new javax.swing.JTextField();
        cbSetConnectionPoints = new javax.swing.JCheckBox();
        cbScatterEdges = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        f_cbRectEdges = new javax.swing.JCheckBox();
        twfWidthTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        f_CBsyncPools = new javax.swing.JCheckBox();
        yDistanceTextFieldBPMN = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        xdistanceTextFieldBPMN = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        f_CBRouteMSF = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        tfLayerDistance = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        showSimpleTypes = new javax.swing.JCheckBox();
        showEnumerations = new javax.swing.JCheckBox();
        showExternalBaseClasses = new javax.swing.JCheckBox();
        colorCodeStereotypes = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        serverStatus1 = new javax.swing.JLabel();
        serverStatus2 = new javax.swing.JLabel();
        serverStopButton = new javax.swing.JButton();
        serverStartButton = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        httpsBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        portField = new javax.swing.JTextField();
        startServerBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuration");

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(300, 200));
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Server Credentials", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setText("Server:");

        jLabel3.setText("User:");

        jLabel5.setText("Password:");

        serverTextField.setText("jTextField1");

        userTextField.setText("jTextField1");

        passwordField.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serverTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(userTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(serverTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General", jPanel13);

        useSystemLookAndFeelCheckbox.setText("Use System Look & Feel (restart required)");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Default Font Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel2.setText("Font:");

        jLabel12.setText("Size:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dialog" }));
        jComboBox1.setEnabled(false);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plain" }));
        jComboBox2.setEnabled(false);

        jLabel13.setText("Style:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "11pt" }));
        jComboBox3.setEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, 326, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(useSystemLookAndFeelCheckbox))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(useSystemLookAndFeelCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Look & Feel", jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 203));

        lPathToDot.setText("DOT executable:");

        pathToDotTextField.setText("dot");

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        animationSpeedTextField.setText("6000");

        lAnimationSpeed.setText("Animation duration:");

        jLabel6.setText("ms");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "UML", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        shortenEdgesBox.setSelected(true);
        shortenEdgesBox.setText("Shorten edges");

        centerNodesbox.setSelected(true);
        centerNodesbox.setText("Center nodes");

        lxDistanceUML.setText("x-Distance between classes");

        lyDistanceUML.setText("y-Distance between classes");

        yDistanceTextFieldUML.setText("35");
        yDistanceTextFieldUML.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                yDistanceTextFieldUMLKeyReleased(evt);
            }
        });

        xdistanceTextFieldUML.setText("30");
        xdistanceTextFieldUML.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                xdistanceTextFieldUMLKeyReleased(evt);
            }
        });

        cbSetConnectionPoints.setSelected(true);
        cbSetConnectionPoints.setText("Set connection points");

        cbScatterEdges.setSelected(true);
        cbScatterEdges.setLabel("scatter Edges");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSetConnectionPoints)
                    .addComponent(lxDistanceUML)
                    .addComponent(shortenEdgesBox)
                    .addComponent(lyDistanceUML))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(centerNodesbox)
                    .addComponent(cbScatterEdges)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(xdistanceTextFieldUML, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(yDistanceTextFieldUML, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(shortenEdgesBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSetConnectionPoints))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(centerNodesbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbScatterEdges)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lxDistanceUML)
                    .addComponent(xdistanceTextFieldUML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yDistanceTextFieldUML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lyDistanceUML))
                .addGap(59, 59, 59))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BPMN/TWF", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel7.setText("max TWF width:");

        f_cbRectEdges.setSelected(true);
        f_cbRectEdges.setText("Rectify edges");

        twfWidthTextField.setText("800");

        jLabel8.setText("px");

        f_CBsyncPools.setText("Align Elements in diff. Pools");

        yDistanceTextFieldBPMN.setText("35");
        yDistanceTextFieldBPMN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                yDistanceTextFieldBPMNKeyReleased(evt);
            }
        });

        jLabel10.setText("x-Distance between elements");

        xdistanceTextFieldBPMN.setText("30");
        xdistanceTextFieldBPMN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                xdistanceTextFieldBPMNKeyReleased(evt);
            }
        });

        jLabel11.setText("y-Distance between elements");

        f_CBRouteMSF.setText("Route Message Flows");
        f_CBRouteMSF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_CBRouteMSFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f_CBRouteMSF)
                    .addComponent(f_CBsyncPools)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(f_cbRectEdges))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(twfWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xdistanceTextFieldBPMN))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yDistanceTextFieldBPMN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(f_cbRectEdges)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(twfWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_CBsyncPools)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_CBRouteMSF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(xdistanceTextFieldBPMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(yDistanceTextFieldBPMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ontologies", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        tfLayerDistance.setText("100");

        jLabel9.setText("Distance of layers:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLayerDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(tfLayerDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lAnimationSpeed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(animationSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lPathToDot)
                        .addGap(18, 18, 18)
                        .addComponent(pathToDotTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPathToDot)
                    .addComponent(pathToDotTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAnimationSpeed)
                    .addComponent(animationSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Layouting", jPanel1);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Import Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        showSimpleTypes.setSelected(true);
        showSimpleTypes.setText("Show simple types as classes");
        showSimpleTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSimpleTypesActionPerformed(evt);
            }
        });

        showEnumerations.setSelected(true);
        showEnumerations.setText("Show enumerations as classes ");

        showExternalBaseClasses.setText("Show external base types as classes");
        showExternalBaseClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showExternalBaseClassesActionPerformed(evt);
            }
        });

        colorCodeStereotypes.setText("Color code stereotypes");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showSimpleTypes)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showExternalBaseClasses)
                            .addComponent(showEnumerations)))
                    .addComponent(colorCodeStereotypes))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(showSimpleTypes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showEnumerations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showExternalBaseClasses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorCodeStereotypes)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("XSD-Import", jPanel3);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel10.setName("Status"); // NOI18N

        serverStatus1.setText(ProcessEditorServer.getInstanceForWorkbench().isRunning() ? "The server is running." : "The server is not running.");

        serverStatus2.setText(ProcessEditorServer.getInstanceForWorkbench().isRunning() ? "URL: " + ProcessEditorServer.getInstanceForWorkbench().getUrl() : "");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serverStatus1)
                    .addComponent(serverStatus2))
                .addContainerGap(382, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(serverStatus1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serverStatus2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        serverStopButton.setText("Stop");
        serverStopButton.setEnabled(ProcessEditorServer.getInstanceForWorkbench().isRunning() );
        serverStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverStopButtonActionPerformed(evt);
            }
        });

        serverStartButton.setEnabled(! ProcessEditorServer.getInstanceForWorkbench().isRunning());
        serverStartButton.setLabel("Start");
        serverStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverStartButtonActionPerformed(evt);
            }
        });

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configuration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        httpsBox.setText("Secure ( HTTPS protocol )");
        httpsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                httpsBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Port:");

        portField.setPreferredSize(new java.awt.Dimension(80, 22));
        portField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                portFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(httpsBox)
                    .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(httpsBox))
        );

        startServerBox.setText("Start server at Workbench start");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startServerBox)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(startServerBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(serverStartButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serverStopButton)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverStartButton)
                    .addComponent(serverStopButton))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Local Server", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, Short.MAX_VALUE)
                    .addComponent(okButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(okButton)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Layouting");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param evt
     */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // Get parameters from all fields, save them and close dialog
        Configuration conf = Configuration.getInstance();
        conf.setProperty(WorkbenchConnectToServerDialog.CONF_SERVER_URI, serverTextField.getText());
        conf.setProperty(WorkbenchConnectToServerDialog.CONF_SERVER_USER, userTextField.getText());
        conf.setProperty(WorkbenchConnectToServerDialog.CONF_SERVER_PASSWORD, new String(passwordField.getPassword()));
        conf.setProperty(Configuration.PROP_DOT_LOCATION, pathToDotTextField.getText().replace("\\", "\\\\"));
        conf.setProperty(Configuration.PROP_USE_SYSTEM_LOOK_AND_FEEL, useSystemLookAndFeelCheckbox.isSelected() ? "1" : "0");
        conf.setProperty(XSDImporter.CONF_SHOW_SIMPLE_CLASSES, showSimpleTypes.isSelected() ? "1" : "0");
        conf.setProperty(XSDImporter.CONF_SHOW_ENUMERATIONS, showEnumerations.isSelected() ? "1" : "0");
        conf.setProperty(XSDImporter.CONF_SHOW_EXTERNAL_BASES_TYPES, showExternalBaseClasses.isSelected() ? "1" : "0");
        conf.setProperty(XSDImporter.CONF_COLOR_CODE_STEREOTYPES, colorCodeStereotypes.isSelected() ? "1" : "0");
        conf.setProperty(LayoutHelper.CONF_SHORTEN_EDGES, shortenEdgesBox.isSelected() ? "1" : "0");
        conf.setProperty(LayoutHelper.CONF_CENTER_NODES, centerNodesbox.isSelected() ? "1" : "0");
        conf.setProperty(LayoutingAnimator.CONF_ANIMATION_SPEED, animationSpeedTextField.getText());
        conf.setProperty(LayoutHelper.CONF_X_DISTANCE_SUGI, xdistanceTextFieldUML.getText());
        conf.setProperty(LayoutHelper.CONF_Y_DISTANCE_SUGI, yDistanceTextFieldUML.getText());
        conf.setProperty(LayoutHelper.CONF_X_DISTANCE_GRID, xdistanceTextFieldBPMN.getText());
        conf.setProperty(LayoutHelper.CONF_Y_DISTANCE_GRID, yDistanceTextFieldBPMN.getText());
        conf.setProperty(LayoutHelper.CONF_MAX_TWF_WIDTH, twfWidthTextField.getText());
        conf.setProperty(LayoutHelper.CONF_RECTIFY, f_cbRectEdges.isSelected() ? "1" : "0");
        conf.setProperty(LayoutHelper.CONF_ROUTE_MESSAGEFLOW, f_CBRouteMSF.isSelected() ? "1":"0");
        conf.setProperty(LayoutHelper.CONF_SYNC_POOLS, f_CBsyncPools.isSelected() ? "1" : "0");
        conf.setProperty(LayoutHelper.CONF_RADIAL_LAYER_DISTANCE, tfLayerDistance.getText());
        conf.setProperty(LayoutHelper.CONF_SET_CONNECTION_POINTS, cbSetConnectionPoints.isSelected() ? "1" : "0");
        conf.setProperty(LayoutHelper.CONF_SCATTER_EDGES, cbScatterEdges.isSelected() ? "1" : "0");
        conf.setProperty(ProcessEditorServer.CONF_SERVER_PORT, portField.getText());
        conf.setProperty(ProcessEditorServer.CONF_SERVER_START_AT_WB_STARTUP, startServerBox.isSelected() ? "1" : "0");
        conf.setProperty(ProcessEditorServerHelper.CONF_SERVER_SECURE, httpsBox.isSelected() ? "1" : "0");
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Open JFileChoose to select dot location
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Select dot executable");

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            pathToDotTextField.setText(chooser.getSelectedFile().getAbsolutePath());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param evt
     */
    private void showExternalBaseClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showExternalBaseClassesActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_showExternalBaseClassesActionPerformed

    /**
     * @param evt
     */
    private void showSimpleTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSimpleTypesActionPerformed
        if (showSimpleTypes.isSelected()) {
            showEnumerations.setEnabled(true);
            showExternalBaseClasses.setEnabled(true);
        } else {
            showEnumerations.setEnabled(false);
            showEnumerations.setSelected(false);
            showExternalBaseClasses.setEnabled(false);
            showExternalBaseClasses.setSelected(false);
        }
    }//GEN-LAST:event_showSimpleTypesActionPerformed

    /**
     * @param evt
     */
    private void yDistanceTextFieldUMLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yDistanceTextFieldUMLKeyReleased
        checkNumericKey(yDistanceTextFieldUML);
}//GEN-LAST:event_yDistanceTextFieldUMLKeyReleased

    /**
     * @param evt
     */
    private void xdistanceTextFieldUMLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xdistanceTextFieldUMLKeyReleased
        checkNumericKey(xdistanceTextFieldUML);
}//GEN-LAST:event_xdistanceTextFieldUMLKeyReleased

    /**
     * @param evt
     */
    private void animationSpeedTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_animationSpeedTextFieldKeyReleased
        checkNumericKey(animationSpeedTextField);
}//GEN-LAST:event_animationSpeedTextFieldKeyReleased

    /**
     *
     * @param evt
     */
    private void xdistanceTextFieldBPMNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xdistanceTextFieldBPMNKeyReleased
        checkNumericKey(xdistanceTextFieldBPMN);
}//GEN-LAST:event_xdistanceTextFieldBPMNKeyReleased
    /**
     * 
     * @param evt
     */
    private void yDistanceTextFieldBPMNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yDistanceTextFieldBPMNKeyReleased
        checkNumericKey(yDistanceTextFieldBPMN);
}//GEN-LAST:event_yDistanceTextFieldBPMNKeyReleased

    /**
	 * @param evt  
	 */
    private void httpsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_httpsBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_httpsBoxActionPerformed

    /**
	 * @param evt  
	 */
    private void serverStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverStartButtonActionPerformed
        try {
            int port = 0;
            try {
                port = Integer.parseInt( portField.getText() );
            } catch (NumberFormatException e) {
                portField.setText(String.valueOf(ProcessEditorServer.DEFAULT_PORT));
                port = ProcessEditorServer.DEFAULT_PORT;
            }


            if (! ProcessEditorServer.isPortInUse(port)) {
                ProcessEditorServer.startForWorkbench(httpsBox.isSelected(), port);
                serverStatus1.setText("The server is running.");
                serverStatus2.setText("URL: " + ProcessEditorServer.getInstanceForWorkbench().getUrl());

                serverStartButton.setEnabled(false);
                serverStopButton.setEnabled(true);

                this.portFieldKeyReleased(null);
            }
        } catch ( Exception ex ) {
            ex.printStackTrace();
        }

}//GEN-LAST:event_serverStartButtonActionPerformed

    /**
	 * @param evt  
	 */
    private void serverStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverStopButtonActionPerformed
        ProcessEditorServer.getInstanceForWorkbench().stop();

        serverStatus1.setText("The server is not running.");
        serverStatus2.setText("");

        serverStopButton.setEnabled(false);
        serverStartButton.setEnabled(true);
        this.portFieldKeyReleased(null);

}//GEN-LAST:event_serverStopButtonActionPerformed

    /**
	 * @param evt  
	 */
    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        this.portFieldKeyReleased(null);
    }//GEN-LAST:event_jTabbedPane1FocusGained

    /**
	 * @param evt  
	 */
    private void portFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_portFieldKeyReleased
        this.checkNumericKey(portField);

        int port;
        try {
            port = Integer.parseInt(portField.getText());
        } catch (NumberFormatException e) {
            port = ProcessEditorServer.DEFAULT_PORT;
            portField.setText(String.valueOf(port));
        }

        if ( port > ProcessEditorServer.MAX_PORT ) {
            portField.setText(portField.getText().substring(0, portField.getText().length() - 1));
            port = Integer.parseInt(portField.getText());
        }
        if ( ProcessEditorServer.isPortInUse(port) )
            portField.setBackground(Color.red);
        else
            portField.setBackground(Color.green);

    }//GEN-LAST:event_portFieldKeyReleased

    private void f_CBRouteMSFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_CBRouteMSFActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_f_CBRouteMSFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField animationSpeedTextField;
    private javax.swing.JCheckBox cbScatterEdges;
    private javax.swing.JCheckBox cbSetConnectionPoints;
    private javax.swing.JCheckBox centerNodesbox;
    private javax.swing.JCheckBox colorCodeStereotypes;
    private javax.swing.JCheckBox f_CBRouteMSF;
    private javax.swing.JCheckBox f_CBsyncPools;
    private javax.swing.JCheckBox f_cbRectEdges;
    private javax.swing.JCheckBox httpsBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lAnimationSpeed;
    private javax.swing.JLabel lPathToDot;
    private javax.swing.JLabel lxDistanceUML;
    private javax.swing.JLabel lyDistanceUML;
    private javax.swing.JButton okButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField pathToDotTextField;
    private javax.swing.JTextField portField;
    private javax.swing.JButton serverStartButton;
    private javax.swing.JLabel serverStatus1;
    private javax.swing.JLabel serverStatus2;
    private javax.swing.JButton serverStopButton;
    private javax.swing.JTextField serverTextField;
    private javax.swing.JCheckBox shortenEdgesBox;
    private javax.swing.JCheckBox showEnumerations;
    private javax.swing.JCheckBox showExternalBaseClasses;
    private javax.swing.JCheckBox showSimpleTypes;
    private javax.swing.JCheckBox startServerBox;
    private javax.swing.JTextField tfLayerDistance;
    private javax.swing.JTextField twfWidthTextField;
    private javax.swing.JCheckBox useSystemLookAndFeelCheckbox;
    private javax.swing.JTextField userTextField;
    private javax.swing.JTextField xdistanceTextFieldBPMN;
    private javax.swing.JTextField xdistanceTextFieldUML;
    private javax.swing.JTextField yDistanceTextFieldBPMN;
    private javax.swing.JTextField yDistanceTextFieldUML;
    // End of variables declaration//GEN-END:variables
}
