/**
 *
 * Process Editor - Core Package
 *
 * (C) 2009 Frank Puhlmann
 *
 * http://frapu.net
 */
package net.frapu.code.visualization;

/**
 *
 * @author fpu
 */
public class ProcessEditorPrintConfigurationDialog extends javax.swing.JDialog {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public enum Status { OK, CANCEL }

    private Status status = Status.CANCEL;

    /** Creates new form ProcessEditorPrintConfigurationDialog */
    public ProcessEditorPrintConfigurationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        printTitleCheckbox = new javax.swing.JCheckBox();
        printCreationDateCheckbox = new javax.swing.JCheckBox();
        printAuthorCheckbox = new javax.swing.JCheckBox();
        printCommentCheckbox = new javax.swing.JCheckBox();
        printUriCheckbox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        borderTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        printGridCheckbox = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configure Print Options");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Print Metadata");

        printTitleCheckbox.setSelected(true);
        printTitleCheckbox.setText("Title");
        printTitleCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printTitleCheckboxActionPerformed(evt);
            }
        });

        printCreationDateCheckbox.setSelected(true);
        printCreationDateCheckbox.setText("Creation Date");

        printAuthorCheckbox.setSelected(true);
        printAuthorCheckbox.setText("Author");

        printCommentCheckbox.setSelected(true);
        printCommentCheckbox.setText("Comment");

        printUriCheckbox.setSelected(true);
        printUriCheckbox.setText("URI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Style");

        jLabel3.setText("Border:");

        borderTextField.setText("0.5");

        jLabel4.setText("inch");

        printGridCheckbox.setSelected(true);
        printGridCheckbox.setText("Print Grid");

        jButton1.setText("Print...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(printTitleCheckbox)
                                .addComponent(printAuthorCheckbox)
                                .addComponent(printCreationDateCheckbox)
                                .addComponent(printGridCheckbox))
                            .addGap(66, 66, 66)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(borderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4))
                                .addComponent(printUriCheckbox)
                                .addComponent(printCommentCheckbox))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printTitleCheckbox)
                    .addComponent(printCommentCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printAuthorCheckbox)
                    .addComponent(printUriCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printCreationDateCheckbox)
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printGridCheckbox)
                    .addComponent(jLabel3)
                    .addComponent(borderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
	 * @param evt  
	 */
    private void printTitleCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printTitleCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printTitleCheckboxActionPerformed

    /**
	 * @param evt  
	 */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setStatus(Status.CANCEL);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
	 * @param evt  
	 */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setStatus(Status.OK);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean isPrintTitle() {
        return printTitleCheckbox.isSelected();
    }

    public boolean isPrintAuthor() {
        return printAuthorCheckbox.isSelected();
    }

    public boolean isPrintComment() {
        return printCommentCheckbox.isSelected();
    }

    public boolean isPrintUri() {
        return printUriCheckbox.isSelected();
    }

    public boolean isPrintCreationDate() {
        return printCreationDateCheckbox.isSelected();
    }

    public boolean isPrintGrid() {
        return printGridCheckbox.isSelected();
    }

    public double getBorderSize() {
        double border = 0.5;
        try {
            border = Double.parseDouble(borderTextField.getText());
        } catch (Exception e) {}
        return border;
    }

    public Status getStatus() {
        return status;
    }

    private void setStatus(Status status) {
        this.status = status;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField borderTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox printAuthorCheckbox;
    private javax.swing.JCheckBox printCommentCheckbox;
    private javax.swing.JCheckBox printCreationDateCheckbox;
    private javax.swing.JCheckBox printGridCheckbox;
    private javax.swing.JCheckBox printTitleCheckbox;
    private javax.swing.JCheckBox printUriCheckbox;
    // End of variables declaration//GEN-END:variables

}
